customer:
    resource: ../../src/Controller/
    type: annotation
    prefix: '/'
Controller:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: '/dashboard'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
