#index:
#    path: /
#    controller: App\Controller\DefaultController::index



home_page:
    path: /dashboard
    # prefix: '/admin'
    controller: App\Controller\TestController::index
app_logout:
    path: /logout
    methods: GET
app_login:
    path: /login
    methods: GET|POST
    controller: App\Controller\LoginController::index