#index:
#    path: /
#    controller: App\Controller\DefaultController::index



home_page:
    path: /dashboard
    # prefix: '/admin'
    controller: App\Controller\TestController::index
client_page:
    path: /
    controller: App\Controller\ClientController::index
category:
    path: /category/{category?}
    methods: GET|POST
    controller: App\Controller\ClientController::category
product:
    path: /product/{product?}
    controller: App\Controller\ClientController::product
app_contact:
    path: /contact
    methods: GET|POST
    controller: App\Controller\ClientController::contact
app_logout:
    path: /logout
    methods: GET
app_login:
    path: /login
    methods: GET|POST
    controller: App\Controller\AuthController::login
app_change_info:
    path: /change-info
    methods: GET|POST
    controller: App\Controller\AuthController::changeInfo
app_change_password:
    path: /change-password
    methods: GET|POST
    controller: App\Controller\AuthController::changePassword
app_register:
    path: /register
    methods: GET|POST
    controller: App\Controller\RegistrationController::register
app_verify_email:
    path: /verify/email
    methods: GET|POST
    controller: App\Controller\RegistrationController::verifyUserEmail
app_forgot_password_request:
    path: /reset-password
    methods: GET|POST
    controller: App\Controller\ResetPasswordController::request
app_check_email:
    path: /check-email
    methods: GET|POST
    controller: App\Controller\ResetPasswordController::checkEmail
app_reset_password:
    path: /reset/{token?}
    controller: App\Controller\ResetPasswordController::reset